apiVersion: v1 
kind: Pod
metadata:
  name: redis 
  labels:
    app: redis
    tier: storage
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
          name: redis-port
