apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote-service
spec:
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: vote-service-port
      nodePort: 30070
  type: NodePort