apiVersion: v1 
kind: Service
metadata:
  name: result-service
  labels:
    app: result-app
spec: 
  selector:
    app: result-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      name: result-service-port
      nodePort: 30080
  type: NodePort
  